### ISSUE TITLE
Блендер

### ISSUE THREAD

**Issue by Voice05** [Voice05/test#1]
Знайти фото блендера

**Comment by VolodymyrTsimbalistyi** [comment]
![tefal_quickchef_8in1_hb65ld38_images_11305296846](https://user-images.githubusercontent.com/53749323/68938264-0ef79800-07af-11ea-99e6-b088f5c75fad.jpg)
![depositphotos_95195554-stock-photo-electric-blender-kitchen-appliance-equipment](https://user-images.githubusercontent.com/53749323/68938285-1ae35a00-07af-11ea-9954-c1247738cd71.jpg)

**Comment by Voice05** [comment]
Done
